server:
  servlet:
    context-path: /crm
  port: 8989
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://127.0.0.1:3306/crm_bak?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  ## freemarker
  freemarker:
    charset: UTF-8
    suffix: .ftl
    template-loader-path: classpath:/views/
    content-type: text/html
## mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.cl.crm.po;com.cl.crm.query;com.cl.crm.dto
## pageHelper
pagehelper:
  helper-dialect: mysql
